In [1]:
#importing modules for the implementation
import pandas as pd
import numpy as np
import sklearn

In [2]:
#pulling the data from the pickled dataset 
nutrition = pd.read_pickle("./nutrition_data_clean.pkl")

In [3]:
#dropping food group and branded columns as they include a lot of NaNs
nutrition.drop(nutrition.columns[1:3], axis=1, inplace=True)
nutrition

,name,Price (£),Weight (GRAMS),Price per Weight (£/100Gram),Carbon Group,Land use (m2/100g),GHG(kgco2eq/100g),Water use (L/100g),Acidifying emissions(kgSO2eq/100g),Eutr emissions (kg PO43-eq per 100g),Calories,Fat (g),Protein (g),Carbohydrate (g),Sugars (g),Fiber (g),Cholesterol (mg),Saturated Fats (g)
0,Pillsbury Cinnamon Rolls With Icing Refrigerat...,1.70,260.0,0.653846,Bread products,0.3482,0.1441,56.7,0.001209,0.000706,330,11.27,4.34,53.42,21.34,1.4,0.0,3.250
1,Waffles Buttermilk Frozen Ready-To-Heat,1.50,567.0,0.264550,Bread products,0.3482,0.1441,56.7,0.001209,0.000706,273,9.22,6.58,41.05,4.30,2.2,15.0,1.898
2,Waffle Buttermilk Frozen Ready-To-Heat Toasted,1.50,567.0,0.264550,Bread products,0.3482,0.1441,56.7,0.001209,0.000706,309,9.49,7.42,48.39,4.41,2.6,13.0,2.275
3,Waffle Buttermilk Frozen Ready-To-Heat Microwaved,1.50,567.0,0.264550,Bread products,0.3482,0.1441,56.7,0.001209,0.000706,289,9.40,6.92,44.16,4.50,2.4,16.0,2.057
4,Waffle Plain Frozen Ready-To-Heat Microwave,1.50,567.0,0.264550,Bread products,0.3482,0.1441,56.7,0.001209,0.000706,298,9.91,6.71,45.41,5.04,2.4,16.0,1.580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1218,Plantain Fried,0.90,85.0,1.058824,Other vegetables,0.0310,0.0455,8.3,0.000531,0.000186,241,10.16,1.66,40.60,19.10,2.9,0.0,1.507
1219,Romaine Lettuce Raw,1.00,400.0,0.250000,Other vegetables,0.0310,0.0455,8.3,0.000531,0.000186,19,0.27,1.39,3.78,0.71,3.1,0.0,0.053
1220,Palak Paneer,3.75,500.0,0.750000,Cheese,8.0642,2.1240,473.5,0.014894,0.008875,96,6.84,5.23,4.32,1.89,1.2,7.0,1.486
1221,Carrots Raw Salad,0.41,1000.0,0.041000,Other vegetables,0.0310,0.0455,8.3,0.000531,0.000186,208,15.70,1.22,17.17,11.23,2.3,9.0,2.452
1222,Corn on the cob,1.50,875.0,0.171429,Other vegetables,0.0310,0.0455,8.3,0.000531,0.000186,67,1.22,2.28,14.30,4.43,2.0,0.0,0.244

In [4]:
#dropping any rows where there is NaNs from any the data set 
nutrition = nutrition.dropna()

In [5]:
#extracting the nutrition data, labelling X as this is the input to the SKlearn algorithm
X = nutrition.iloc[:,10:]
X

,Calories,Fat (g),Protein (g),Carbohydrate (g),Sugars (g),Fiber (g),Cholesterol (mg),Saturated Fats (g)
0,330,11.27,4.34,53.42,21.34,1.4,0.0,3.250
1,273,9.22,6.58,41.05,4.30,2.2,15.0,1.898
2,309,9.49,7.42,48.39,4.41,2.6,13.0,2.275
3,289,9.40,6.92,44.16,4.50,2.4,16.0,2.057
4,298,9.91,6.71,45.41,5.04,2.4,16.0,1.580
...,...,...,...,...,...,...,...,...
1218,241,10.16,1.66,40.60,19.10,2.9,0.0,1.507
1219,19,0.27,1.39,3.78,0.71,3.1,0.0,0.053
1220,96,6.84,5.23,4.32,1.89,1.2,7.0,1.486
1221,208,15.70,1.22,17.17,11.23,2.3,9.0,2.452
1222,67,1.22,2.28,14.30,4.43,2.0,0.0,0.244

In [6]:
#extracting the greenhouse gas emissions 
y = nutrition.iloc[:,6:7]
y

      GHG(kgco2eq/100g)
0                0.1441
1                0.1441
2                0.1441
3                0.1441
4                0.1441
...                 ...
1218             0.0455
1219             0.0455
1220             2.1240
1221             0.0455
1222             0.0455

[1189 rows x 1 columns]

In [7]:
#splitting the dataset into a test and training data set, with 20% being used for testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2) #size =0.2 means 80% data is training data, 20% testing

In [14]:
#importing sklearn algorithm and using it with 2000 trees 
#storing the prediction from the test 
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=10, random_state=0)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

C:\Users\han\miniconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """

In [18]:
#find a way to make the GHG emissions a 1d list 

y_train.shape
y_train[:10]

      GHG(kgco2eq/100g)
112              0.1441
1088             0.5752
680              0.0750
737              0.7282
1103             0.0365
428              1.6477
227              0.1441
494              0.0988
981              5.9570
1173             0.1427

In [15]:
#evaluating the model by checking errors
#generally error decreases slightly as number of trees is increased, converges around 200 trees

from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.3677276344537814
Mean Squared Error: 0.6698949296921047
Root Mean Squared Error: 0.8184710927651048

In [16]:
np.mean(y)
np.std(y)

GHG(kgco2eq/100g)    1.666654
dtype: float64

In [ ]:
#work out stadnard deviation

In [ ]:
# bagging and boosting perform on the carbon set
# boosting split it into mini data sub sections 
# adding in more of the data 


# different number of trees a for loop