In [1]:
#importing modules for the implementation
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt 
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib as mpl

In [29]:
#pulling the data from the pickled dataset 
nutrition = pd.read_pickle("./WHOLEnutrition_data_clean.pkl")
nutrition

,ID,name,Food Group,Branded?,Price (£),Weight (GRAMS),Price per 100 grams (£/100g),Carbon Group,Land use (m2/kg),GHG(kgco2eq/kg),...,Serving Description 5 (g),Serving Weight 6 (g),Serving Description 6 (g),Serving Weight 7 (g),Serving Description 7 (g),Serving Weight 8 (g),Serving Description 8 (g),Serving Weight 9 (g),Serving Description 9 (g),200 Calorie Weight (g)
0,167513,Pillsbury Cinnamon Rolls With Icing Refrigerat...,Baked Foods,NaN,1.70,260.0,0.653846,Bread products,3.482,1.441,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.606
1,167516,Waffles Buttermilk Frozen Ready-To-Heat,Baked Foods,X,1.50,567.0,0.264550,Bread products,3.482,1.441,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.260
2,167517,Waffle Buttermilk Frozen Ready-To-Heat Toasted,Baked Foods,X,1.50,567.0,0.264550,Bread products,3.482,1.441,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.725
3,167518,Waffle Buttermilk Frozen Ready-To-Heat Microwaved,Baked Foods,X,1.50,567.0,0.264550,Bread products,3.482,1.441,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.204
4,167519,Waffle Plain Frozen Ready-To-Heat Microwave,Baked Foods,X,1.50,567.0,0.264550,Bread products,3.482,1.441,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1218,787165,Plantain Fried,Vegetables,NaN,0.90,85.0,1.058824,Other vegetables,0.310,0.455,...,1 small order,162.0,1 medium order,284.0,1 large order,169.0,1 cup,23.0,1 linear inch,82.988
1219,787271,Romaine Lettuce Raw,Vegetables,NaN,1.00,400.0,0.250000,Other vegetables,0.310,0.455,...,NaN,13.0,"1 leaf, romaine",10.0,"1 leaf, escarole",9.0,"1 leaf, endive",292.0,"1 small head, endive",1052.632
1220,787408,Palak Paneer,Vegetables,NaN,3.75,500.0,0.750000,Cheese,80.642,21.240,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,208.333
1221,787523,Carrots Raw Salad,Vegetables,NaN,0.41,1000.0,0.041000,Other vegetables,0.310,0.455,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.154
1222,788186,Corn on the cob,Vegetables,NaN,1.50,875.0,0.171429,Other vegetables,0.310,0.455,...,"1 oz, canned, yields",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,298.507

In [30]:
#dropping food group and branded columns as they include a lot of NaNs
nutrition.drop(nutrition.columns[[1,2,3,24,30,31,32,33,34,35,36,43,44,45,46,47,48,49,50,51,52,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84]], axis=1, inplace=True)
nutrition

,ID,Price (£),Weight (GRAMS),Price per 100 grams (£/100g),Carbon Group,Land use (m2/kg),GHG(kgco2eq/kg),Water use(L/kg),Acidifying emissions(kgSO2eq/kg),Eutr emissions (kg PO43-eq per kg,...,Serving Description 5 (g),Serving Weight 6 (g),Serving Description 6 (g),Serving Weight 7 (g),Serving Description 7 (g),Serving Weight 8 (g),Serving Description 8 (g),Serving Weight 9 (g),Serving Description 9 (g),200 Calorie Weight (g)
0,167513,1.70,260.0,0.653846,Bread products,3.482,1.441,567.0,0.01209,0.00706,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.606
1,167516,1.50,567.0,0.264550,Bread products,3.482,1.441,567.0,0.01209,0.00706,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.260
2,167517,1.50,567.0,0.264550,Bread products,3.482,1.441,567.0,0.01209,0.00706,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.725
3,167518,1.50,567.0,0.264550,Bread products,3.482,1.441,567.0,0.01209,0.00706,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.204
4,167519,1.50,567.0,0.264550,Bread products,3.482,1.441,567.0,0.01209,0.00706,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1218,787165,0.90,85.0,1.058824,Other vegetables,0.310,0.455,83.0,0.00531,0.00186,...,1 small order,162.0,1 medium order,284.0,1 large order,169.0,1 cup,23.0,1 linear inch,82.988
1219,787271,1.00,400.0,0.250000,Other vegetables,0.310,0.455,83.0,0.00531,0.00186,...,NaN,13.0,"1 leaf, romaine",10.0,"1 leaf, escarole",9.0,"1 leaf, endive",292.0,"1 small head, endive",1052.632
1220,787408,3.75,500.0,0.750000,Cheese,80.642,21.240,4735.0,0.14894,0.08875,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,208.333
1221,787523,0.41,1000.0,0.041000,Other vegetables,0.310,0.455,83.0,0.00531,0.00186,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.154
1222,788186,1.50,875.0,0.171429,Other vegetables,0.310,0.455,83.0,0.00531,0.00186,...,"1 oz, canned, yields",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,298.507

In [32]:
#dropping food group and branded columns as they include a lot of NaNs
nutrition.drop(nutrition.columns[36:], axis=1, inplace=True)
nutrition

,ID,Price (£),Weight (GRAMS),Price per 100 grams (£/100g),Carbon Group,Land use (m2/kg),GHG(kgco2eq/kg),Water use(L/kg),Acidifying emissions(kgSO2eq/kg),Eutr emissions (kg PO43-eq per kg,...,Trans Fatty Acids (g),Soluble Fiber (g),Insoluble Fiber (g),Sucrose (g),Glucose (Dextrose) (g),Fructose (g),"Selenium, Se (mcg)","Fluoride, F (mcg)",Molybdenum (mcg),Chlorine (mg)
0,167513,1.70,260.0,0.653846,Bread products,3.482,1.441,567.0,0.01209,0.00706,...,4.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,167516,1.50,567.0,0.264550,Bread products,3.482,1.441,567.0,0.01209,0.00706,...,NaN,NaN,NaN,2.67,0.00,0.0,9.5,NaN,NaN,NaN
2,167517,1.50,567.0,0.264550,Bread products,3.482,1.441,567.0,0.01209,0.00706,...,NaN,NaN,NaN,2.85,0.05,0.0,10.3,NaN,NaN,NaN
3,167518,1.50,567.0,0.264550,Bread products,3.482,1.441,567.0,0.01209,0.00706,...,NaN,NaN,NaN,2.77,0.00,0.0,10.1,NaN,NaN,NaN
4,167519,1.50,567.0,0.264550,Bread products,3.482,1.441,567.0,0.01209,0.00706,...,NaN,NaN,NaN,3.31,0.00,0.0,12.8,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1218,787165,0.90,85.0,1.058824,Other vegetables,0.310,0.455,83.0,0.00531,0.00186,...,NaN,NaN,NaN,NaN,NaN,NaN,1.9,NaN,NaN,NaN
1219,787271,1.00,400.0,0.250000,Other vegetables,0.310,0.455,83.0,0.00531,0.00186,...,NaN,NaN,NaN,NaN,NaN,NaN,0.3,NaN,NaN,NaN
1220,787408,3.75,500.0,0.750000,Cheese,80.642,21.240,4735.0,0.14894,0.08875,...,NaN,NaN,NaN,NaN,NaN,NaN,3.9,NaN,NaN,NaN
1221,787523,0.41,1000.0,0.041000,Other vegetables,0.310,0.455,83.0,0.00531,0.00186,...,NaN,NaN,NaN,NaN,NaN,NaN,0.6,NaN,NaN,NaN
1222,788186,1.50,875.0,0.171429,Other vegetables,0.310,0.455,83.0,0.00531,0.00186,...,NaN,NaN,NaN,NaN,NaN,NaN,0.6,NaN,NaN,NaN

In [5]:
#extracting the nutrition data, labelling X as this is the input to the SKlearn algorithm
X = nutrition.iloc[:,10:]
X

,Calories,Fat (g),Protein (g),Carbohydrate (g),Sugars (g),Fiber (g),Cholesterol (mg),Saturated Fats (g)
0,330,11.27,4.34,53.42,21.34,1.4,0.0,3.250
1,273,9.22,6.58,41.05,4.30,2.2,15.0,1.898
2,309,9.49,7.42,48.39,4.41,2.6,13.0,2.275
3,289,9.40,6.92,44.16,4.50,2.4,16.0,2.057
4,298,9.91,6.71,45.41,5.04,2.4,16.0,1.580
...,...,...,...,...,...,...,...,...
1218,241,10.16,1.66,40.60,19.10,2.9,0.0,1.507
1219,19,0.27,1.39,3.78,0.71,3.1,0.0,0.053
1220,96,6.84,5.23,4.32,1.89,1.2,7.0,1.486
1221,208,15.70,1.22,17.17,11.23,2.3,9.0,2.452
1222,67,1.22,2.28,14.30,4.43,2.0,0.0,0.244

In [6]:
#extracting the greenhouse gas emissions 
y = nutrition.iloc[:,6:7]
y

      GHG(kgco2eq/100g)
0                0.1441
1                0.1441
2                0.1441
3                0.1441
4                0.1441
...                 ...
1218             0.0455
1219             0.0455
1220             2.1240
1221             0.0455
1222             0.0455

[1189 rows x 1 columns]

In [7]:
#changing y to a 1d array rather than the table 
y = np.ravel(y)
y

array([0.1441, 0.1441, 0.1441, ..., 2.124 , 0.0455, 0.0455])

In [8]:
#splitting the dataset into a test and train data set, with 20% being used for testing
from sklearn.model_selection import train_test_split
X_train_val, X_test, y_train_val, y_test = train_test_split(X,y,test_size=0.2) #size =0.2 means 80% data is training data, 20% testing

In [9]:
#splitting train data set into train and validation set 
X_train, X_val, y_train, y_val = train_test_split(X_train_val,y_train_val,test_size=0.15)

In [10]:
#importing sklearn algorithm and using it with 2000 trees 
#storing the prediction from the test 
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=10, random_state=0)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [11]:
#evaluating the model by checking errors
#generally error decreases slightly as number of trees is increased, converges around 200 trees

from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.5179168991596638
Mean Squared Error: 1.1896215647783452
Root Mean Squared Error: 1.0906977421716546

In [12]:
np.mean(y)

0.885288393608074

In [13]:
np.std(y)

1.666653780717875

In [19]:
# bagging and boosting perform on the carbon set
# boosting split it into mini data sub sections 
# adding in more of the data 


# different number of trees a for loop

In [42]:
#writing a for loop to pull out the error at varying n_estimators (otherwise known as the number of trees the algorithm is using)


mse = []
mae = []
rmse = []
        
for i in range(1,200,5):
    from sklearn.ensemble import RandomForestRegressor
    model = RandomForestRegressor(n_estimators=i, random_state=0)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    Mean_Absolute_Error = metrics.mean_absolute_error(y_test, y_pred)
    Mean_Squared_Error = metrics.mean_squared_error(y_test, y_pred)
    Root_Mean_Squared_Error = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
   
    mse.append(Mean_Squared_Error)
    rmse.append(Root_Mean_Squared_Error)
    mae.append(Mean_Absolute_Error)

NameError: name 'fig' is not defined